language: go
script:
  - make deps
  - make depslint
  - make lint
  - make test
  - make cross

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux